version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: another-blog-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h2fx7Bn5wlO4x3Sk
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
